# Generated by Django 2.2.3 on 2019-07-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='locations',
            field=models.ManyToManyField(to='advertisements.Location'),
        ),
    ]
