# Generated by Django 2.2.3 on 2019-07-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20190715_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='name',
        ),
    ]
