# Generated by Django 2.2.3 on 2019-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_auto_20190716_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='thumbnail',
            field=models.CharField(default='https://getuikit.com/v2/docs/images/placeholder_600x400.svg', max_length=100),
            preserve_default=False,
        ),
    ]
