# Generated by Django 2.2.3 on 2019-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_auto_20190721_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
