# Generated by Django 2.2.3 on 2019-08-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_auto_20190826_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='homepage_appeared_in',
            field=models.IntegerField(default=0),
        ),
    ]
