# Generated by Django 2.2.3 on 2019-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0013_auto_20190829_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
        migrations.AddField(
            model_name='support',
            name='email',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
    ]
