# Generated by Django 2.2.3 on 2019-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0014_auto_20190829_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='iso',
            field=models.CharField(default='Not Set', max_length=15),
            preserve_default=False,
        ),
    ]
