# Generated by Django 2.2.3 on 2019-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0015_location_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='product_page_link',
            field=models.URLField(max_length=5000),
        ),
    ]
